# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-30 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttt', models.CharField(max_length=32)),
                ('kkk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo')),
            ],
        ),
    ]
