# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20170906_0929'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Some',
            new_name='Hobby',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mm',
            field=models.ManyToManyField(to='app01.Some', verbose_name='选多个'),
        ),
    ]
