# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-11 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arya', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='app_label',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='app_name',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='args',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='name',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='query_params',
        ),
    ]
